### PR TITLE
Create new release to make src folder available in package

### PR DESCRIPTION
**Pull request by byjs-dev**
We need the src folder for the ZBM locationfinder app. It also makes sense for future development to just pick the modules and things that are needed.

### CODE REVIEW

**Comment by sebbuku** [comment]
:+1:

**Comment by cabutler10** [comment]
@byjs-dev @sebbuku However if we merge into master than we push npm package up to 2.0, not a big deal but maybe we could remove the semantic release part since we aren't working on this project full time? it would be nice to merge all into master and have it go up just by smaller increments instead. Thoughts?

**Comment by sebbuku** [comment]
> @byjs-dev @sebbuku However if we merge into master than we push npm package up to 2.0, not a big deal but maybe we could remove the semantic release part since we aren't working on this project full time? it would be nice to merge all into master and have it go up just by smaller increments instead. Thoughts?

It won't bump it to 2.0 if you don't sign a `major` in a commit or indicate breaking changes. So it will stay at 1.* for the moment.

**Comment by sebbuku** [comment]
> > @byjs-dev @sebbuku However if we merge into master than we push npm package up to 2.0, not a big deal but maybe we could remove the semantic release part since we aren't working on this project full time? it would be nice to merge all into master and have it go up just by smaller increments instead. Thoughts?
> 
> It won't bump it to 2.0 if you don't sign a `major` in a commit or indicate breaking changes. So it will stay at 1.* for the moment.

### BREAKING CHANGES

    * button: color name changes

There will be a 2.0 release. I wouldn't release it yet until it's done or we have beta tag for the release.
Let's discuss this in the CoP. @cabutler10 @byjs-dev @esseladjei

**Pull request merged**
