### PR TITLE
WIP: chore(code-style): fix linter errors preventing build

### PR DESCRIPTION
**Pull request by Flameforge**
Add a script to package.json that allows the Fixing of prettier linter errors.
Apply that script and fix build/deploy linter errors on Master.

### CODE REVIEW

**Comment by Flameforge** [comment]
These Prettier tests were already failing in Master branch.

Screenshot 2020-09-29 at 16 51 51

**Review by cabutler10 — APPROVED** [review]

**Review by cabutler10 — CHANGES_REQUESTED** [review]
I am concerned that this is not necessary since we already have Husky. I would like to bring this to the table at COP. 

Also, before merging, I would like to see all packages updated.

**Comment by byjs-dev** [comment]
@Flameforge I'm totally fine with the PR. 
@cabutler10 I also agree to talk about that in the COP to have a common understanding.

**Review by byjs-dev — APPROVED** [review]

**Comment by byjs-dev** [comment]
I'm currently working on a loading spinner that Julian Kohr provided us. He wants me to add it to the ZDS. While working on that, I merged this branch into my working branch and everything works like a charm. This is why I'm just merging this now.

**Pull request merged**
