### PR TITLE
Loading spinner

### PR DESCRIPTION
**Pull request by byjs-dev**
Just added the loading spinner that Julian Kohr provided for the ZDS (from Avengers Team request for location-finder-view)

image

### CODE REVIEW

**Review by cabutler10 — APPROVED** [review]

**Comment by byjs-dev** [comment]
FYI: I published a "next" version to npm

npmjs

**Comment by cabutler10** [comment]
Do we need a next? I know theoretically it would be better, but in practice, we have breaking changes with pretty much every push. Also, we don't have any roadmap to a new level so in my opinion, its just easier to always bump it up without worrying about a next.

**Comment by byjs-dev** [comment]
> Do we need a next? I know theoretically it would be better, but in practice, we have breaking changes with pretty much every push. Also, we don't have any roadmap to a new level so in my opinion, its just easier to always bump it up without worrying about a next.

This is just because I published locally - to be able to use this right away. Maybe we'll have some refactoring after review & before merging. I can not use the semantic release process here after merging into develop either, because of the huge open PR (https://github.com/zepdev/zeppelin-element-library/pull/151). We have to solve this before. (Yeah, I know - we should have done this a looooong time ago ;))

**Comment by cabutler10** [comment]
Ah, no I totally understand. However for about the past 50 changes I have made, I always just push locally without the whole semantic release stuff since we don't have a true roadmap.

**Pull request merged**
