### PR TITLE
feat(number-input): Added new number-input component

### PR DESCRIPTION
**Pull request by sebbuku**

### CODE REVIEW

**Comment by sebbuku** [comment]
Please look carefully. I'm not sure if this is the right way to go about this.

**Comment by cabutler10** [comment]
1)Couple of issues with the padding, i think we need to clarify with sasha, looks like the pagination and this input have slightly different sizes?
2)Please make sure that the import './icons.font' is NOT commented out
3)we need a class for the icon to make sure it is a fixed width/height and color

**Comment by sebbuku** [comment]
Should all be fixed now.
Regarding the fonts import the line is also commented out on the development branch: https://github.com/zepdev/zeppelin-element-library/blob/development/src/App.js#L6

**Comment by cabutler10** [comment]
'./icons.font' needs to be uncommented, its wrong on dev

**Comment by sebbuku** [comment]
@cabutler10 noted. I re-enabled it and also switched to icon font.

**Comment by cabutler10** [comment]
@sebbuku the font is wrong on the number input, should be roboto at 16px

**Comment by sebbuku** [comment]
Ok, I isolated the icons in a separate css. @cabutler10 you can re-use that for your checkbox.

**Pull request merged**
