### PR TITLE
Issue/168 automate svg optimization and sprite creation

### PR DESCRIPTION
**Pull request by byjs-dev**

### CODE REVIEW

**Review by cabutler10 — COMMENTED** [review]
substract needs to be changed to subtract

how come some icons are filled with purple?

also one icon appears to have the name 'C51497E4-FEA3-4563-8907-A227752FFE71@1x' in sprite/icons.svg?

why keep a folder of SVG and raw? can we remove one?

**Comment by byjs-dev** [comment]
> substract needs to be changed to subtract
> 
> 
> 
> how come some icons are filled with purple?
> 
> 
> 
> also one icon appears to have the name 'C51497E4-FEA3-4563-8907-A227752FFE71@1x' in sprite/icons.svg?
> 
> 
> 
> why keep a folder of SVG and raw? can we remove one?
> 
> 

Now it's subtract. :)

I had a discussion with Julian about the location icons and them being themed and so on. The Icons are just used individually in maps and can then be colorized manually. We are open to change it, if there is a use case.

The weird icon name in the sprite should be gone now, after the latest commit.

And yes we can delete the raw folder after processing, or at least it's files. I'll do the changes tomorrow. 

Thanks!

**Comment by byjs-dev** [comment]
I chose to keep the icons/raw/ folder with the raw files to allow certain changes in there. The build process will run the svg processing and use all contents from the raw folder for the final svg and sprite result (e.g. only one .svg in /raw results in one .svg in /SVG and in the sprite). If the raw folder is missing or empty, the SVG processing won't start.

**Review by cabutler10 — APPROVED** [review]

**Comment by byjs-dev** [comment]
@ms-zlab I just need your review for the svghandler.sh (https://github.com/zepdev/zeppelin-element-library/pull/172/files#diff-8615d107afecba6a139c59388f4c330045372dfc70acca69bc3f76db9199afc3), that's it. ;) thx

**Review by esseladjei — COMMENTED** [review]
1. "browserslist": svgo property in package.json not a string
2. cannot cd into  cd "$DIR_PATH"/src/assets/icons/SVG
3. create_svg_sprite function call breaks due to the point 2
4. svgo: command not found even after yarn install 

All other items looks good . Code structure is top class , with proper formatting and function and with clear sepration of concerns

**Comment by byjs-dev** [comment]
> 1. "browserslist": svgo property in package.json not a string
Sorry I don't understand - can you please give more detailed info on that

> 2. cannot cd into  cd "$DIR_PATH"/src/assets/icons/SVG
> 3. create_svg_sprite function call breaks due to the point 2
> 4. svgo: command not found even after yarn install
Let's take a look at it together on your machine, so I'll have a better understanding of these issues. Just ping me. :)

**Review by esseladjei — APPROVED** [review]

**Comment by byjs-dev** [comment]
> @esseladjei
> 
> > 1. "browserslist": svgo property in package.json not a string
> >    Sorry I don't understand - can you please give more detailed info on that
> 
> > 1. cannot cd into  cd "$DIR_PATH"/src/assets/icons/SVG
> > 2. create_svg_sprite function call breaks due to the point 2
> > 3. svgo: command not found even after yarn install
> >    Let's take a look at it together on your machine, so I'll have a better understanding of these issues. Just ping me. :)

Here is a brief summary of the solution:
1. browserslist : svgo -> no issue here, was just a github review mistake. 
2. & 3. svgo was installed: Please don't call ./svghandler directly, instead use the yarn command "yarn svg:update" as provided in the package.json, this solved the path issue. ;) 

The svg update step is also documented in the README.md

**Pull request merged**
